% folders = string({'cceACECalculatedLevel', ...
%     'cceACEFeedProfilePOLS_All', ...
%     'cceACEFeedProfileSixInLine_WSML', ...
%     'cceACEFeedProfile_SCF', ...
%     'cceACEGenTo2Total', ...
%     'cceACERampTo2Total', ...
%     'cceACEUSMLFurnaceFeed', ...
%     'cceAceContRampTo2Total'});

folderDir = dir("Converted Calculations");
folders = strings(1,size(folderDir,1));

for i = 3:size(folderDir,1)
    folders(i) = folderDir(i).name;
end

folders(1:2) = [];

for folderName = folders
    buildACE(folderName)
end
