function [p1, p2, p3, p4] = shadingClassification(indices1,indices2, indices3,indices4,...
        dataTbl, ymin, ymax)
    %UNTITLED3 Summary of this function goes here
    %   Detailed explanation goes here
    p1 = patch(NaN, NaN, 'r', 'FaceAlpha', 0.1);
    p2 = patch(NaN, NaN, 'g', 'FaceAlpha', 0.1);
    p3 = patch(NaN, NaN, 'b', 'FaceAlpha', 0.1);
    p4 = patch(NaN, NaN, 'y', 'FaceAlpha', 0.1);


    groupedIndices1 = find(diff([0; indices1; 0]));  % Find start and end of each continuous true region
    for i = 1:2:length(groupedIndices1)-1  % Iterate over each region
        fill([dataTbl.Timestamp(groupedIndices1(i):groupedIndices1(i+1)); ...
            flipud(dataTbl.Timestamp(groupedIndices1(i):groupedIndices1(i+1)))],...
            [repmat(ymin, groupedIndices1(i+1)-groupedIndices1(i)+1, 1); ...
            repmat(ymax, groupedIndices1(i+1)-groupedIndices1(i)+1, 1)],...
            'r', 'FaceAlpha', 0.1, 'EdgeColor', 'none');  % Fill region
    end

    groupedIndices2 = find(diff([0; indices2; 0]));  % Find start and end of each continuous true region
    for i = 1:2:length(groupedIndices2)-1  % Iterate over each region
        if groupedIndices2(i+1) < height(dataTbl)
            fill([dataTbl.Timestamp(groupedIndices2(i):groupedIndices2(i+1)); ...
                flipud(dataTbl.Timestamp(groupedIndices2(i):groupedIndices2(i+1)))],...
                [repmat(ymin, groupedIndices2(i+1)-groupedIndices2(i)+1, 1); ...
                repmat(ymax, groupedIndices2(i+1)-groupedIndices2(i)+1, 1)],...
                'g', 'FaceAlpha', 0.1, 'EdgeColor', 'none');  % Fill region
        end
    end

    groupedIndices3 = find(diff([0; indices3; 0]));  % Find start and end of each continuous true region
    for i = 1:2:length(groupedIndices3)-1  % Iterate over each region
        if groupedIndices3(i+1) < height(dataTbl)
            fill([dataTbl.Timestamp(groupedIndices3(i):groupedIndices3(i+1)); ...
                flipud(dataTbl.Timestamp(groupedIndices3(i):groupedIndices3(i+1)))],...
                [repmat(ymin, groupedIndices3(i+1)-groupedIndices3(i)+1, 1); ...
                repmat(ymax, groupedIndices3(i+1)-groupedIndices3(i)+1, 1)],...
                'b', 'FaceAlpha', 0.1, 'EdgeColor', 'none');  % Fill region
        end
    end

    groupedIndices4 = find(diff([0; indices4; 0]));  % Find start and end of each continuous true region
    for i = 1:2:length(groupedIndices4)-1  % Iterate over each region
        if groupedIndices4(i+1) < height(dataTbl)
            fill([dataTbl.Timestamp(groupedIndices4(i):groupedIndices4(i+1)); ...
                flipud(dataTbl.Timestamp(groupedIndices4(i):groupedIndices4(i+1)))],...
                [repmat(ymin, groupedIndices4(i+1)-groupedIndices4(i)+1, 1); ...
                repmat(ymax, groupedIndices4(i+1)-groupedIndices4(i)+1, 1)],...
                'y', 'FaceAlpha', 0.1, 'EdgeColor', 'none');  % Fill region
        end
    end
end