function parameters = loadSlagTapRatesParameters()

parameters.SlagConveyorMoisture = 0.2;
parameters.MoistureCalibrationPeriod = 2.5; % Period in days over which
% to perform the slag moisture fitting.

parameters.simMode = "simulation";
parameters.LogName = fullfile(getpref('PolokwaneSIL', 'DataFolder'), "logs", "LevelModel.log");
parameters.CalculationID = 'TestLM';
parameters.LogLevel = 255;
parameters.CalculationName = 'TestLevelModel';
parameters.OutputTime = "2024-10-09T08:00:01.000Z";

parameters.ExecutionFrequencyParam = 30;
parameters.relativeTimeRange = parameters.MoistureCalibrationPeriod * 24 * 60;

parameters.MoistureCalibrationPeriod = 2.5;
parameters.ThermalTappingThreshold = 1200;

parameters.tags = ["Timestamp",...
"MatteTapRatesTonPerHr",...
"SlagConveyorMass",...
"DiverterIsToConveyorEast",...
"DiverterIsToConveyorCenter",...
"DiverterIsToConveyorWest",...
"SlagMassFromEnergyBalanceEast",...
"SlagMassFromEnergyBalanceCenter",...
"SlagMassFromEnergyBalanceWest",...
"FeedTonPerHr",...
"SlagTap1ThermalCameraTemp",...
"SlagTap2ThermalCameraTemp",...
"SlagTap3ThermalCameraTemp",...
"Temp_412_TT_002",...
"Temp_412_TT_007",...
"Temp_412_TT_008",...
"Temp_412_TT_009",...
"Flow_412_FT_201",...
"Flow_412_FT_301",...
"Flow_412_FT_401",...
"CWFlowRate",...
"CWInletTemp",...
"CWOutletTemp",...
"CombinedValidDeltaSounding",...
"NewMeanMattePlusBuildupThickness",...
"NewMeanSlagThickness",...
"NewMeanConcThickness",...
];

end