function parameters = loadPolokwaneSILParameters()

parameters.simMode = "simulation";
parameters.LogName = fullfile(getpref('PolokwaneSIL', 'DataFolder'), "logs", "LevelModel.log");
parameters.CalculationID = 'TestLM';
parameters.LogLevel = 255;
parameters.CalculationName = 'TestLevelModel';
parameters.OutputTime = "2024-10-09T08:00:01.000Z";

parameters.ExecutionFrequencyParam = 30;
parameters.relativeTimeRange = 31;

parameters.SoundingTimeMin = 6;
parameters.SoundingTimeMax = 7;

parameters.tags = [
"Timestamp",...
"MatteFallFraction",...
"PowerMw",...
"SEC12HrKwhPerTon",...
"FeedTonPerHr",...
"MatteTapRatesTonPerHr",...
"CombinedValidDeltaSounding",...
"NewMeanMattePlusBuildupThickness",...
"NewMeanSlagThickness",...
"NewMeanConcThickness",...
"NewMeanTotalLiquidThickness",...
"SlagTapRates"
];
end