function parameters = loadSoundingValuesParameters()
parameters.simMode = "simulation";
parameters.LogName = fullfile(getpref('PolokwaneSIL', 'DataFolder'), "logs", "LevelModel.log");
parameters.CalculationID = 'TestLM';
parameters.LogLevel = 255;
parameters.CalculationName = 'TestLevelModel';
parameters.OutputTime = "2024-10-09T08:00:01.000Z";

parameters.relativeTimeRange = 60*5; % Minutes
parameters.ExecutionFrequencyParam = 30; % Minutes

parameters.tags = [
"Timestamp",...
"BuildUpSoundingPort1",...
"BuildUpSoundingPort2",...
"BuildUpSoundingPort3",...
"BuildUpSoundingPort4",...
"BuildUpSoundingPort5",...
"BuildUpSoundingPort6",...
"BuildUpSoundingPort7",...
"BuildUpSoundingPort8",...
"BuildUpSoundingPort10",...
"MatteSoundingPort1",...
"MatteSoundingPort2",...
"MatteSoundingPort3",...
"MatteSoundingPort4",...
"MatteSoundingPort5",...
"MatteSoundingPort6",...
"MatteSoundingPort7",...
"MatteSoundingPort8",...
"MatteSoundingPort10",...
"SlagSoundingPort1",...
"SlagSoundingPort2",...
"SlagSoundingPort3",...
"SlagSoundingPort4",...
"SlagSoundingPort5",...
"SlagSoundingPort6",...
"SlagSoundingPort7",...
"SlagSoundingPort8",...
"SlagSoundingPort10",...
"ConcentrateSoundingPort1",...
"ConcentrateSoundingPort2",...
"ConcentrateSoundingPort3",...
"ConcentrateSoundingPort4",...
"ConcentrateSoundingPort5",...
"ConcentrateSoundingPort6",...
"ConcentrateSoundingPort7",...
"ConcentrateSoundingPort8",...
"ConcentrateSoundingPort10",...
];

end