'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


'Original file name:
'Generation date: 2013/05/20 01:18:32 PM
Namespace StreamDataDomainServiceData
    '''<summary>
    '''There are no comments for StreamDataDomainServiceData in the schema.
    '''</summary>
    Partial Public Class StreamDataDomainServiceData
        Inherits Global.System.Data.Services.Client.DataServiceContext
        '''<summary>
        '''Initialize a new StreamDataDomainServiceData object.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub New(ByVal serviceRoot As Global.System.Uri)
            MyBase.New(serviceRoot)
            Me.ResolveName = AddressOf Me.ResolveNameFromType
            Me.ResolveType = AddressOf Me.ResolveTypeFromName
            Me.OnContextCreated
        End Sub
        Partial Private Sub OnContextCreated()
        End Sub
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private Shared ROOTNAMESPACE As String = GetType(StreamDataDomainServiceData).Namespace.Remove(GetType(StreamDataDomainServiceData).Namespace.LastIndexOf("StreamDataDomainServiceData"))
        '''<summary>
        '''Since the namespace configured for this service reference
        '''in Visual Studio is different from the one indicated in the
        '''server schema, use type-mappers to map between the two.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Function ResolveTypeFromName(ByVal typeName As String) As Global.System.Type
            If typeName.StartsWith("LightSwitchApplication", Global.System.StringComparison.OrdinalIgnoreCase) Then
                Return Me.GetType.Assembly.GetType(String.Concat(String.Concat(ROOTNAMESPACE, "StreamDataDomainServiceData"), typeName.Substring(22)), false)
            End If
            Return Nothing
        End Function
        '''<summary>
        '''Since the namespace configured for this service reference
        '''in Visual Studio is different from the one indicated in the
        '''server schema, use type-mappers to map between the two.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Function ResolveNameFromType(ByVal clientType As Global.System.Type) As String
            If clientType.Namespace.Equals(String.Concat(ROOTNAMESPACE, "StreamDataDomainServiceData"), Global.System.StringComparison.OrdinalIgnoreCase) Then
                Return String.Concat("LightSwitchApplication.", clientType.Name)
            End If
            Return Nothing
        End Function
        '''<summary>
        '''There are no comments for WBrawDatas in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property WBrawDatas() As Global.System.Data.Services.Client.DataServiceQuery(Of WBrawData)
            Get
                If (Me._WBrawDatas Is Nothing) Then
                    Me._WBrawDatas = MyBase.CreateQuery(Of WBrawData)("WBrawDatas")
                End If
                Return Me._WBrawDatas
            End Get
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _WBrawDatas As Global.System.Data.Services.Client.DataServiceQuery(Of WBrawData)
        '''<summary>
        '''There are no comments for MArawDatas in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property MArawDatas() As Global.System.Data.Services.Client.DataServiceQuery(Of MArawData)
            Get
                If (Me._MArawDatas Is Nothing) Then
                    Me._MArawDatas = MyBase.CreateQuery(Of MArawData)("MArawDatas")
                End If
                Return Me._MArawDatas
            End Get
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _MArawDatas As Global.System.Data.Services.Client.DataServiceQuery(Of MArawData)
        '''<summary>
        '''There are no comments for TransactionSummaries in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property TransactionSummaries() As Global.System.Data.Services.Client.DataServiceQuery(Of TransactionSummary)
            Get
                If (Me._TransactionSummaries Is Nothing) Then
                    Me._TransactionSummaries = MyBase.CreateQuery(Of TransactionSummary)("TransactionSummaries")
                End If
                Return Me._TransactionSummaries
            End Get
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _TransactionSummaries As Global.System.Data.Services.Client.DataServiceQuery(Of TransactionSummary)
        '''<summary>
        '''There are no comments for StreamTotals in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property StreamTotals() As Global.System.Data.Services.Client.DataServiceQuery(Of StreamTotal)
            Get
                If (Me._StreamTotals Is Nothing) Then
                    Me._StreamTotals = MyBase.CreateQuery(Of StreamTotal)("StreamTotals")
                End If
                Return Me._StreamTotals
            End Get
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _StreamTotals As Global.System.Data.Services.Client.DataServiceQuery(Of StreamTotal)
        '''<summary>
        '''There are no comments for WBrawDatas in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToWBrawDatas(ByVal wBrawData As WBrawData)
            MyBase.AddObject("WBrawDatas", wBrawData)
        End Sub
        '''<summary>
        '''There are no comments for MArawDatas in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToMArawDatas(ByVal mArawData As MArawData)
            MyBase.AddObject("MArawDatas", mArawData)
        End Sub
        '''<summary>
        '''There are no comments for TransactionSummaries in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToTransactionSummaries(ByVal transactionSummary As TransactionSummary)
            MyBase.AddObject("TransactionSummaries", transactionSummary)
        End Sub
        '''<summary>
        '''There are no comments for StreamTotals in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToStreamTotals(ByVal streamTotal As StreamTotal)
            MyBase.AddObject("StreamTotals", streamTotal)
        End Sub
    End Class
    '''<summary>
    '''There are no comments for LightSwitchApplication.WBrawData in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.DataServiceKeyAttribute("ID")>  _
    Partial Public Class WBrawData
        '''<summary>
        '''Create a new WBrawData object.
        '''</summary>
        '''<param name="ID">Initial value of ID.</param>
        '''<param name="dateIn">Initial value of DateIn.</param>
        '''<param name="dateOut">Initial value of DateOut.</param>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateWBrawData(ByVal ID As Integer, ByVal dateIn As Date, ByVal dateOut As Date) As WBrawData
            Dim wBrawData As WBrawData = New WBrawData()
            wBrawData.ID = ID
            wBrawData.DateIn = dateIn
            wBrawData.DateOut = dateOut
            Return wBrawData
        End Function
        '''<summary>
        '''There are no comments for Property ID in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID() As Integer
            Get
                Return Me._ID
            End Get
            Set
                Me.OnIDChanging(value)
                Me._ID = value
                Me.OnIDChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID As Integer
        Partial Private Sub OnIDChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property DateIn in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property DateIn() As Date
            Get
                Return Me._DateIn
            End Get
            Set
                Me.OnDateInChanging(value)
                Me._DateIn = value
                Me.OnDateInChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _DateIn As Date
        Partial Private Sub OnDateInChanging(ByVal value As Date)
        End Sub
        Partial Private Sub OnDateInChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property DateOut in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property DateOut() As Date
            Get
                Return Me._DateOut
            End Get
            Set
                Me.OnDateOutChanging(value)
                Me._DateOut = value
                Me.OnDateOutChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _DateOut As Date
        Partial Private Sub OnDateOutChanging(ByVal value As Date)
        End Sub
        Partial Private Sub OnDateOutChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Lot in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Lot() As Global.System.Nullable(Of Integer)
            Get
                Return Me._Lot
            End Get
            Set
                Me.OnLotChanging(value)
                Me._Lot = value
                Me.OnLotChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Lot As Global.System.Nullable(Of Integer)
        Partial Private Sub OnLotChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnLotChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Batch in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Batch() As Global.System.Nullable(Of Integer)
            Get
                Return Me._Batch
            End Get
            Set
                Me.OnBatchChanging(value)
                Me._Batch = value
                Me.OnBatchChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Batch As Global.System.Nullable(Of Integer)
        Partial Private Sub OnBatchChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnBatchChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Nett in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Nett() As Global.System.Nullable(Of Double)
            Get
                Return Me._Nett
            End Get
            Set
                Me.OnNettChanging(value)
                Me._Nett = value
                Me.OnNettChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Nett As Global.System.Nullable(Of Double)
        Partial Private Sub OnNettChanging(ByVal value As Global.System.Nullable(Of Double))
        End Sub
        Partial Private Sub OnNettChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Gross in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Gross() As Global.System.Nullable(Of Double)
            Get
                Return Me._Gross
            End Get
            Set
                Me.OnGrossChanging(value)
                Me._Gross = value
                Me.OnGrossChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Gross As Global.System.Nullable(Of Double)
        Partial Private Sub OnGrossChanging(ByVal value As Global.System.Nullable(Of Double))
        End Sub
        Partial Private Sub OnGrossChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property WBCode in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property WBCode() As String
            Get
                Return Me._WBCode
            End Get
            Set
                Me.OnWBCodeChanging(value)
                Me._WBCode = value
                Me.OnWBCodeChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _WBCode As String
        Partial Private Sub OnWBCodeChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnWBCodeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property TruckReg in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property TruckReg() As String
            Get
                Return Me._TruckReg
            End Get
            Set
                Me.OnTruckRegChanging(value)
                Me._TruckReg = value
                Me.OnTruckRegChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _TruckReg As String
        Partial Private Sub OnTruckRegChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnTruckRegChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property TrailerReg in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property TrailerReg() As String
            Get
                Return Me._TrailerReg
            End Get
            Set
                Me.OnTrailerRegChanging(value)
                Me._TrailerReg = value
                Me.OnTrailerRegChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _TrailerReg As String
        Partial Private Sub OnTrailerRegChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnTrailerRegChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property HaulerName in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property HaulerName() As String
            Get
                Return Me._HaulerName
            End Get
            Set
                Me.OnHaulerNameChanging(value)
                Me._HaulerName = value
                Me.OnHaulerNameChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _HaulerName As String
        Partial Private Sub OnHaulerNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnHaulerNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property SampleID in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property SampleID() As String
            Get
                Return Me._SampleID
            End Get
            Set
                Me.OnSampleIDChanging(value)
                Me._SampleID = value
                Me.OnSampleIDChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _SampleID As String
        Partial Private Sub OnSampleIDChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnSampleIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property VehicleType in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property VehicleType() As String
            Get
                Return Me._VehicleType
            End Get
            Set
                Me.OnVehicleTypeChanging(value)
                Me._VehicleType = value
                Me.OnVehicleTypeChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _VehicleType As String
        Partial Private Sub OnVehicleTypeChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnVehicleTypeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property stBatch in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property stBatch() As String
            Get
                Return Me._stBatch
            End Get
            Set
                Me.OnstBatchChanging(value)
                Me._stBatch = value
                Me.OnstBatchChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _stBatch As String
        Partial Private Sub OnstBatchChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnstBatchChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property stLot in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property stLot() As String
            Get
                Return Me._stLot
            End Get
            Set
                Me.OnstLotChanging(value)
                Me._stLot = value
                Me.OnstLotChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _stLot As String
        Partial Private Sub OnstLotChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnstLotChanged()
        End Sub
    End Class
    '''<summary>
    '''There are no comments for LightSwitchApplication.MArawData in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.DataServiceKeyAttribute("ID")>  _
    Partial Public Class MArawData
        '''<summary>
        '''Create a new MArawData object.
        '''</summary>
        '''<param name="ID">Initial value of ID.</param>
        '''<param name="sampleDate">Initial value of SampleDate.</param>
        '''<param name="lot">Initial value of Lot.</param>
        '''<param name="batch">Initial value of Batch.</param>
        '''<param name="value">Initial value of Value.</param>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateMArawData(ByVal ID As Integer, ByVal sampleDate As Date, ByVal lot As Integer, ByVal batch As Integer, ByVal value As Double) As MArawData
            Dim mArawData As MArawData = New MArawData()
            mArawData.ID = ID
            mArawData.SampleDate = sampleDate
            mArawData.Lot = lot
            mArawData.Batch = batch
            mArawData.Value = value
            Return mArawData
        End Function
        '''<summary>
        '''There are no comments for Property ID in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID() As Integer
            Get
                Return Me._ID
            End Get
            Set
                Me.OnIDChanging(value)
                Me._ID = value
                Me.OnIDChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID As Integer
        Partial Private Sub OnIDChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property SampleDate in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property SampleDate() As Date
            Get
                Return Me._SampleDate
            End Get
            Set
                Me.OnSampleDateChanging(value)
                Me._SampleDate = value
                Me.OnSampleDateChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _SampleDate As Date
        Partial Private Sub OnSampleDateChanging(ByVal value As Date)
        End Sub
        Partial Private Sub OnSampleDateChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Lot in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Lot() As Integer
            Get
                Return Me._Lot
            End Get
            Set
                Me.OnLotChanging(value)
                Me._Lot = value
                Me.OnLotChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Lot As Integer
        Partial Private Sub OnLotChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnLotChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Batch in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Batch() As Integer
            Get
                Return Me._Batch
            End Get
            Set
                Me.OnBatchChanging(value)
                Me._Batch = value
                Me.OnBatchChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Batch As Integer
        Partial Private Sub OnBatchChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnBatchChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Value in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Value() As Double
            Get
                Return Me._Value
            End Get
            Set
                Me.OnValueChanging(value)
                Me._Value = value
                Me.OnValueChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Value As Double
        Partial Private Sub OnValueChanging(ByVal value As Double)
        End Sub
        Partial Private Sub OnValueChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Plantcode in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Plantcode() As String
            Get
                Return Me._Plantcode
            End Get
            Set
                Me.OnPlantcodeChanging(value)
                Me._Plantcode = value
                Me.OnPlantcodeChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Plantcode As String
        Partial Private Sub OnPlantcodeChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnPlantcodeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property MACode in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property MACode() As String
            Get
                Return Me._MACode
            End Get
            Set
                Me.OnMACodeChanging(value)
                Me._MACode = value
                Me.OnMACodeChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _MACode As String
        Partial Private Sub OnMACodeChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnMACodeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Assay in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Assay() As String
            Get
                Return Me._Assay
            End Get
            Set
                Me.OnAssayChanging(value)
                Me._Assay = value
                Me.OnAssayChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Assay As String
        Partial Private Sub OnAssayChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnAssayChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Timecode in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Timecode() As String
            Get
                Return Me._Timecode
            End Get
            Set
                Me.OnTimecodeChanging(value)
                Me._Timecode = value
                Me.OnTimecodeChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Timecode As String
        Partial Private Sub OnTimecodeChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnTimecodeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property stBatch in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property stBatch() As String
            Get
                Return Me._stBatch
            End Get
            Set
                Me.OnstBatchChanging(value)
                Me._stBatch = value
                Me.OnstBatchChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _stBatch As String
        Partial Private Sub OnstBatchChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnstBatchChanged()
        End Sub
    End Class
    '''<summary>
    '''There are no comments for LightSwitchApplication.TransactionSummary in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.DataServiceKeyAttribute("ID")>  _
    Partial Public Class TransactionSummary
        '''<summary>
        '''Create a new TransactionSummary object.
        '''</summary>
        '''<param name="ID">Initial value of ID.</param>
        '''<param name="isEstimate">Initial value of IsEstimate.</param>
        '''<param name="c_Date">Initial value of c_Date.</param>
        '''<param name="lot">Initial value of Lot.</param>
        '''<param name="periodTotal">Initial value of PeriodTotal.</param>
        '''<param name="periodAverage">Initial value of PeriodAverage.</param>
        '''<param name="dayTotal">Initial value of DayTotal.</param>
        '''<param name="dayAverage">Initial value of DayAverage.</param>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateTransactionSummary(ByVal ID As Integer, ByVal isEstimate As Boolean, ByVal c_Date As Date, ByVal lot As Integer, ByVal periodTotal As Double, ByVal periodAverage As Double, ByVal dayTotal As Double, ByVal dayAverage As Double) As TransactionSummary
            Dim transactionSummary As TransactionSummary = New TransactionSummary()
            transactionSummary.ID = ID
            transactionSummary.IsEstimate = isEstimate
            transactionSummary.c_Date = c_Date
            transactionSummary.Lot = lot
            transactionSummary.PeriodTotal = periodTotal
            transactionSummary.PeriodAverage = periodAverage
            transactionSummary.DayTotal = dayTotal
            transactionSummary.DayAverage = dayAverage
            Return transactionSummary
        End Function
        '''<summary>
        '''There are no comments for Property ID in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID() As Integer
            Get
                Return Me._ID
            End Get
            Set
                Me.OnIDChanging(value)
                Me._ID = value
                Me.OnIDChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID As Integer
        Partial Private Sub OnIDChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property WBStream in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property WBStream() As String
            Get
                Return Me._WBStream
            End Get
            Set
                Me.OnWBStreamChanging(value)
                Me._WBStream = value
                Me.OnWBStreamChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _WBStream As String
        Partial Private Sub OnWBStreamChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnWBStreamChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property MAStream in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property MAStream() As String
            Get
                Return Me._MAStream
            End Get
            Set
                Me.OnMAStreamChanging(value)
                Me._MAStream = value
                Me.OnMAStreamChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _MAStream As String
        Partial Private Sub OnMAStreamChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnMAStreamChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Direction in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Direction() As String
            Get
                Return Me._Direction
            End Get
            Set
                Me.OnDirectionChanging(value)
                Me._Direction = value
                Me.OnDirectionChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Direction As String
        Partial Private Sub OnDirectionChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnDirectionChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property SourcePlant in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property SourcePlant() As String
            Get
                Return Me._SourcePlant
            End Get
            Set
                Me.OnSourcePlantChanging(value)
                Me._SourcePlant = value
                Me.OnSourcePlantChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _SourcePlant As String
        Partial Private Sub OnSourcePlantChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnSourcePlantChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property PlantStreams in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property PlantStreams() As String
            Get
                Return Me._PlantStreams
            End Get
            Set
                Me.OnPlantStreamsChanging(value)
                Me._PlantStreams = value
                Me.OnPlantStreamsChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _PlantStreams As String
        Partial Private Sub OnPlantStreamsChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnPlantStreamsChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property DestPlant in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property DestPlant() As String
            Get
                Return Me._DestPlant
            End Get
            Set
                Me.OnDestPlantChanging(value)
                Me._DestPlant = value
                Me.OnDestPlantChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _DestPlant As String
        Partial Private Sub OnDestPlantChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnDestPlantChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Material in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Material() As String
            Get
                Return Me._Material
            End Get
            Set
                Me.OnMaterialChanging(value)
                Me._Material = value
                Me.OnMaterialChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Material As String
        Partial Private Sub OnMaterialChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnMaterialChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property MatCategory in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property MatCategory() As String
            Get
                Return Me._MatCategory
            End Get
            Set
                Me.OnMatCategoryChanging(value)
                Me._MatCategory = value
                Me.OnMatCategoryChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _MatCategory As String
        Partial Private Sub OnMatCategoryChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnMatCategoryChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property IsEstimate in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property IsEstimate() As Boolean
            Get
                Return Me._IsEstimate
            End Get
            Set
                Me.OnIsEstimateChanging(value)
                Me._IsEstimate = value
                Me.OnIsEstimateChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _IsEstimate As Boolean
        Partial Private Sub OnIsEstimateChanging(ByVal value As Boolean)
        End Sub
        Partial Private Sub OnIsEstimateChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property c_Date in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property c_Date() As Date
            Get
                Return Me._c_Date
            End Get
            Set
                Me.Onc_DateChanging(value)
                Me._c_Date = value
                Me.Onc_DateChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _c_Date As Date
        Partial Private Sub Onc_DateChanging(ByVal value As Date)
        End Sub
        Partial Private Sub Onc_DateChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Lot in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Lot() As Integer
            Get
                Return Me._Lot
            End Get
            Set
                Me.OnLotChanging(value)
                Me._Lot = value
                Me.OnLotChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Lot As Integer
        Partial Private Sub OnLotChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnLotChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property UOM in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property UOM() As String
            Get
                Return Me._UOM
            End Get
            Set
                Me.OnUOMChanging(value)
                Me._UOM = value
                Me.OnUOMChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _UOM As String
        Partial Private Sub OnUOMChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnUOMChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Assay in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Assay() As String
            Get
                Return Me._Assay
            End Get
            Set
                Me.OnAssayChanging(value)
                Me._Assay = value
                Me.OnAssayChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Assay As String
        Partial Private Sub OnAssayChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnAssayChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Description in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Description() As String
            Get
                Return Me._Description
            End Get
            Set
                Me.OnDescriptionChanging(value)
                Me._Description = value
                Me.OnDescriptionChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Description As String
        Partial Private Sub OnDescriptionChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnDescriptionChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property PeriodTotal in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property PeriodTotal() As Double
            Get
                Return Me._PeriodTotal
            End Get
            Set
                Me.OnPeriodTotalChanging(value)
                Me._PeriodTotal = value
                Me.OnPeriodTotalChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _PeriodTotal As Double
        Partial Private Sub OnPeriodTotalChanging(ByVal value As Double)
        End Sub
        Partial Private Sub OnPeriodTotalChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property PeriodAverage in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property PeriodAverage() As Double
            Get
                Return Me._PeriodAverage
            End Get
            Set
                Me.OnPeriodAverageChanging(value)
                Me._PeriodAverage = value
                Me.OnPeriodAverageChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _PeriodAverage As Double
        Partial Private Sub OnPeriodAverageChanging(ByVal value As Double)
        End Sub
        Partial Private Sub OnPeriodAverageChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property DayTotal in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property DayTotal() As Double
            Get
                Return Me._DayTotal
            End Get
            Set
                Me.OnDayTotalChanging(value)
                Me._DayTotal = value
                Me.OnDayTotalChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _DayTotal As Double
        Partial Private Sub OnDayTotalChanging(ByVal value As Double)
        End Sub
        Partial Private Sub OnDayTotalChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property DayAverage in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property DayAverage() As Double
            Get
                Return Me._DayAverage
            End Get
            Set
                Me.OnDayAverageChanging(value)
                Me._DayAverage = value
                Me.OnDayAverageChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _DayAverage As Double
        Partial Private Sub OnDayAverageChanging(ByVal value As Double)
        End Sub
        Partial Private Sub OnDayAverageChanged()
        End Sub
    End Class
    '''<summary>
    '''There are no comments for LightSwitchApplication.StreamTotal in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.DataServiceKeyAttribute("ID")>  _
    Partial Public Class StreamTotal
        '''<summary>
        '''Create a new StreamTotal object.
        '''</summary>
        '''<param name="ID">Initial value of ID.</param>
        '''<param name="day">Initial value of Day.</param>
        '''<param name="result">Initial value of Result.</param>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateStreamTotal(ByVal ID As Integer, ByVal day As Date, ByVal result As Double) As StreamTotal
            Dim streamTotal As StreamTotal = New StreamTotal()
            streamTotal.ID = ID
            streamTotal.Day = day
            streamTotal.Result = result
            Return streamTotal
        End Function
        '''<summary>
        '''There are no comments for Property ID in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID() As Integer
            Get
                Return Me._ID
            End Get
            Set
                Me.OnIDChanging(value)
                Me._ID = value
                Me.OnIDChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID As Integer
        Partial Private Sub OnIDChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property StreamTotalName in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property StreamTotalName() As String
            Get
                Return Me._StreamTotalName
            End Get
            Set
                Me.OnStreamTotalNameChanging(value)
                Me._StreamTotalName = value
                Me.OnStreamTotalNameChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _StreamTotalName As String
        Partial Private Sub OnStreamTotalNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnStreamTotalNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Day in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Day() As Date
            Get
                Return Me._Day
            End Get
            Set
                Me.OnDayChanging(value)
                Me._Day = value
                Me.OnDayChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Day As Date
        Partial Private Sub OnDayChanging(ByVal value As Date)
        End Sub
        Partial Private Sub OnDayChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Result in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Result() As Double
            Get
                Return Me._Result
            End Get
            Set
                Me.OnResultChanging(value)
                Me._Result = value
                Me.OnResultChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Result As Double
        Partial Private Sub OnResultChanging(ByVal value As Double)
        End Sub
        Partial Private Sub OnResultChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property UOM in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property UOM() As String
            Get
                Return Me._UOM
            End Get
            Set
                Me.OnUOMChanging(value)
                Me._UOM = value
                Me.OnUOMChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _UOM As String
        Partial Private Sub OnUOMChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnUOMChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property PITag in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property PITag() As String
            Get
                Return Me._PITag
            End Get
            Set
                Me.OnPITagChanging(value)
                Me._PITag = value
                Me.OnPITagChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _PITag As String
        Partial Private Sub OnPITagChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnPITagChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ItemToCalc in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ItemToCalc() As String
            Get
                Return Me._ItemToCalc
            End Get
            Set
                Me.OnItemToCalcChanging(value)
                Me._ItemToCalc = value
                Me.OnItemToCalcChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ItemToCalc As String
        Partial Private Sub OnItemToCalcChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnItemToCalcChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property CalcType in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property CalcType() As String
            Get
                Return Me._CalcType
            End Get
            Set
                Me.OnCalcTypeChanging(value)
                Me._CalcType = value
                Me.OnCalcTypeChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _CalcType As String
        Partial Private Sub OnCalcTypeChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnCalcTypeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Message in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Message() As String
            Get
                Return Me._Message
            End Get
            Set
                Me.OnMessageChanging(value)
                Me._Message = value
                Me.OnMessageChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Message As String
        Partial Private Sub OnMessageChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnMessageChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Plant in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Plant() As String
            Get
                Return Me._Plant
            End Get
            Set
                Me.OnPlantChanging(value)
                Me._Plant = value
                Me.OnPlantChanged
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Plant As String
        Partial Private Sub OnPlantChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnPlantChanged()
        End Sub
    End Class
End Namespace
