# This is the main deployment configuration file for CCE.
# In development, modify this file only in the build folder, not the deploy folder.
# These comments, as well as some settings, should be carefully considered prior to final deployment.

# TODO: Document this configuration file better!

[System]
    ServiceType = "AF"
    CCEUsername = "cceServer"
    CCEPassword = "EU8vEKmd1k8+xkKnvZIAi1DxE5PyxlwBTdkrCTuRrdeM9gv+LkHfyMobCkYKABP9"
    SchedulerFolderName = "CCE"
    LogFileMaxSize = 20
    LogFileBackupLimit = 20
[CalculationDB]
    ServerName = "ons-opcdev.optinum.local"
    DBName = "CCEProd"
[CoordinatorDB]
    ServerName = "ons-opcdev.optinum.local"
    DBName = "CCEProd"
[Configurator]
    TestMode = 1
    LogFile = "configurator.log"
    LogLevel = "Trace"
[Coordinator]
    MaxCalculationLoad = 10
    Lifetime = 43200
    LifetimeOverrunPercentage = 10
    FrequencyLimit = 600
    LogFile = "coordinator.log"
    LogLevel = "Warning"
[CalculationServer]
    HostName = "ons-opcdev"
    Port = 9910
    AutoDeployFolder = "cceCalcServerDeploy"
    RequestTimeout = 1
