buildCalc("timeSeriesPrediction", {"D:\Opti-Num\Projects\CCE\calculationSupport\calculations\neuralNets\timeSeriesPrediction\predict.m", ...
    "D:\Opti-Num\Projects\CCE\calculationSupport\calculations\neuralNets\timeSeriesPrediction\trainNet.m"}, ...
    "D:\Opti-Num\Projects\CCE\calculationSupport\calculations\neuralNets\timeSeriesPrediction\net.mat")