function inputs = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  POLSILDATA20241004S1 = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  POLSILDATA20241004S1 = IMPORTFILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  POLSILDATA20241004S1 = IMPORTFILE(FILE, SHEET, DATALINES) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  POLSILData20241004S1 = importfile("D:\eunice\Projects\Amplats\SIL Furnace Modelling\data\POL_SIL_Data_20241004.xlsx", "Sheet2", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Oct-2024 08:16:33

%% Input handling

% If no sheet is specified, read from Sheet2
if nargin == 1 || isempty(sheetName)
    sheetName = "Sheet2";
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 18);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% % Specify column names and types
opts.VariableNamingRule =  "preserve";
opts.VariableNamesRange  = 1;
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "categorical", "categorical", "double", "double", "double", "double", "double", "double"];

% Import the data
inputs = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    inputs = [inputs; tb]; %#ok<AGROW>
end

end