function slInputs = preprocessTemperatureData(inputs)
%PREPROCESSTEMPERATUREDATA takes in a timetable and:
% Removes invalid rows
% Constructs outputs needed for energy balances

% Change TimeStamp to duration
inputs.Timestamp = inputs.Timestamp - inputs.Timestamp(1);

% Convert table to timetable
inputs = table2timetable(inputs, 'RowTimes', 'Timestamp');

% Set all negative electrode power to NaN
inputs.PowerMw(inputs.PowerMw < 0) = 0;

% Calculate a mean slag and temperature while ignoring low values
inputs.SlagTemp = calcTempFromCameras(inputs(:,{'SlagTap1ThermalCameraTemp', ...
    'SlagTap2ThermalCameraTemp', 'SlagTap3ThermalCameraTemp'}), 1200, 30, 2);

inputs.MatteTemp = calcTempFromCameras(inputs(:,{'MatteTap1ThermalCameraTemp', ...
    'MatteTap2ThermalCameraTemp', 'MatteTap3ThermalCameraTemp'}), 1200, 30, 4);

% % Removes invalid rows
% inputs = rmmissing(inputs);

% Prepare output
slInputs = struct( ...
    T_slag = rmmissing(inputs(:, 'SlagTemp')), ...
    T_matte = rmmissing(inputs(:, 'MatteTemp')), ...
    Wdot_electrode_MW = rmmissing(inputs(:, 'PowerMw')), ...
    mdot_cw = rmmissing(inputs(:, 'CWFlowRate')), ...
    T_cw_out = rmmissing(inputs(:, 'CWOutletTemp')), ...
    T_cw_in = rmmissing(inputs(:, 'CWInletTemp')),...
    T_air_west_in = rmmissing(inputs(:, 'AirTempInWest')),...
    T_air_hearth_in = rmmissing(inputs(:, 'AirTempInHearth')),...
    T_air_east_in = rmmissing(inputs(:, 'AirTempInEast')),...
    T_air_west_out = rmmissing(inputs(:, 'AirTempOutWest')),...
    T_air_hearth_out = rmmissing(inputs(:, 'AirTempOutHearth')),...
    T_air_east_out = rmmissing(inputs(:, 'AirTempOutEast'))...
    );

end