function parameters = getTempModelParameters(parameters, data, logger)
%GETTEMPMODELPARAMETERS Reads in temperature model parameters

parameters.highFrequencyPredictorTags = ["MattefeedPV", "FuelcoalfeedratePV",...
    "SpecificOxygenActualPV", "RevertsfeedratePV", "LumpcoalPV",...
    "LanceoxygenflowratePV", "LanceairflowratePV",...
    "Mattetransferairflow", "Lancecoalcarrierair",...
    "Lancemotion", "SilicaPV",...
    "UpperWaffle3", "UpperWaffle4", "UpperWaffle5",...
    "UpperWaffle6", "UpperWaffle7", "UpperWaffle8",...
    "UpperWaffle9", "UpperWaffle10", "UpperWaffle11",...
    "UpperWaffle12", "UpperWaffle13", "UpperWaffle14",...
    "UpperWaffle15", "UpperWaffle16", "UpperWaffle17",...
    "UpperWaffle18",...
    "Lowerwaffle19", "Lowerwaffle20", "Lowerwaffle21",...
    "Lowerwaffle22", "Lowerwaffle23", "Lowerwaffle24",...
    "Lowerwaffle25", "Lowerwaffle26", "Lowerwaffle27",...
    "Lowerwaffle28", "Lowerwaffle29", "Lowerwaffle30",...
    "Lowerwaffle31", "Lowerwaffle32", "Lowerwaffle33",...
    "Lowerwaffle34", "LanceOxyEnrichPercentagePV", "RoofmattefeedratePV",...
    "Lanceheight", "PhaseBMattetapblock1DT_water",...
    "PhaseBMattetapblock2DT_water", "PhaseBSlagtapblockDT_water",...
    "PhaseAMattetapblock1DT_water", "PhaseAMattetapblockDT_water",...
    "PhaseASlagtapblockDT_water"];

parameters.lowFrequencyPredictorTags = ["Cr2O3Slag", "Basicity", "MgOSlag",...
    "CuFeedblend", "NiFeedblend",...
    "CoFeedblend", "FeFeedblend", "SFeedblend",...
    "SiO2Feedblend", "Al2O3Feedblend", "CaOFeedblend",...
    "MgOFeedblend", "Cr2O3Feedblend", "Slagtemperatures"];

parameters.referenceTags = ["Convertermode", "Lanceairandoxygencontrol",...
    "SlagFlowThermo"];

parameters.responseTags = ["Mattetemperatures"];

% filterFurnaceModes.add = false;
parameters.filterFurnaceModes = 8;

% parameters.filterFurnaceModes = filterFurnaceModes;

parameters.simVar = getSimvars(data, parameters, logger);

end


