# CCE Test Infrastructure Configuration File
#   This configuration works for all tests. Do not use this configuration outside of testing.
#   If you need a Dev configuration, use WACP:
#       >> cce.dev.setCCERoot("dev")
[System]
    ServiceType = "AF"
    CCEUsername = "cceServer"
    CCEPassword = "REDACTED_WON'T_WORK"
    SchedulerFolderName = "CCE"
    LogFileMaxSize = 20
    LogFileBackupLimit = 20
[CalculationDB]
    ServerName = "ons-opcdev.optinum.local"
    DBName = "CCETest_05_07_2023"
[CoordinatorDB]
    ServerName = "ons-opcdev.optinum.local"
    DBName = "CCETest_05_07_2023"
[Configurator]
    # TestMode - Tell the configurator to load but not write anything but a log file
    TestMode = 0
    LogFile = "configurator.log"
    LogLevel = "Info"
[Coordinator]
    MaxCalculationLoad = 5
    Lifetime = 43200
    LifetimeOverrunPercentage = 10
    FrequencyLimit = 600
    LogFile = "coordinator.log"
    LogLevel = "All"
[CalculationServer]
	HostName = "ons-opcdev"
    Port = 9910
	AutoDeployFolder = "cceCalcServerDeploy"
    RequestTimeout = 5
